inherits = "naysayer"

# Override the theming for "keyword"s:
"ui.cursor.match" = ""

"warning" = { fg = "#ffdd33", modifiers = ["bold"] }
"error" = { fg = "#ffdd33", modifiers = ["bold"] }
"info" = { fg = "#ffdd33", modifiers = ["bold"] }
"hint" = { fg = "#ffdd33", modifiers = ["bold"] }
"note" = { fg = "#ffdd33", modifiers = ["bold"] }
"todo" = { fg = "#ffdd33", modifiers = ["bold"] }
"refactor" = { fg = "#ffdd33", modifiers = ["bold"] }

