version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

	[[blocks.segments]]
		type = 'path'
		style = 'plain'
		background = 'transparent'
		foreground = 'p:white'

		[blocks.segments.properties]
		style = 'full'

	[[blocks.segments]]
		type = 'text'
		style = 'plain'
		foreground_templates = [
			"{{if gt .Code 0}}p:red{{end}}",
			"{{if eq .Code 0}}p:green{{end}}",
		]
		background = 'transparent'
		template = '❯'

	[[blocks.segments]]
		type = 'git'
		style = 'plain'
		background = 'transparent'
		foreground = 'p:git'
		    template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>'

		[blocks.segments.properties]
		branch_icon = ''
		commit_icon = '@'
		fetch_status = true

[[blocks]]
	type = 'rprompt'
	overflow = 'hidden'

	[[blocks.segments]]
		type = 'executiontime'	
		style = 'plain'
		foreground = 'yellow'
		background = 'transparent'
		template = '{{ div .Ms 1000 }}s'

		[blocks.segments.properties]
			threshold = 5000

[palette]
white = '#FFFFFF'
red = '#f43841'
green = '#7CC138'
git = '#6c6c6c'
